services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - NODE_ENV=production
    # depends_on:
    #   - backend

  # Backend service (to be added later)
  # backend:
  #   build: ./backend
  #   ports:
  #     - "${BACKEND_PORT}:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  #   depends_on:
  #     - db

  # Database service (to be added later)
  # db:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./data/postgres-data:/var/lib/postgresql/data